# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Game.create(title: 'Final Fantasy XV', description: 'Get ready to be at the centre of the ultimate fantasy adventure. Enter the world of FINAL FANTASY XV, and experience epic action-packed battles along your journey of discovery. You are Noctis, the Crown Prince of the Kingdom of Lucis, and your quest is to reclaim your homeland from the clutches of the imperial army. Joined by your closest friends, you will take the wheel and experience a voyage like no other, travelling through the breath-taking world of Eos encountering larger-than-life beasts and unforgiving enemies. You will learn to master the skills of weaponry and magic, channelling the power of your ancestors allowing you to effortlessly warp through the air in thrilling combat. Fresh faces and long-time fans, fulfil your destiny and experience a brand new kind of fantasy. Pre-order the Day One Edition to receive the exclusive FINAL FANTASY series weapon', ESRB: 'T', link: '<iframe width="560" height="315" src="https://www.youtube.com/embed/SZymd6r4wGg?ecver=1" frameborder="0" allowfullscreen></iframe>')
Game.create(title: 'The Elder Scrolls V: Skyrim', description: 'The main story revolves around the player character and their quest to defeat Alduin the World-Eater, a dragon who is prophesied to destroy the world. The game is set two hundred years after the events of Oblivion, and takes place in the fictional province of Skyrim. Over the course of the game, the player completes quests and develops the character by improving skills. The game continues the open world tradition of its predecessors by allowing the player to travel anywhere in the game world at any time, and to ignore or postpone the main storyline indefinitely.', ESRB: 'M', link: '<iframe width="560" height="315" src="https://www.youtube.com/embed/JSRtYpNRoN0?ecver=1" frameborder="0" allowfullscreen></iframe>')
Game.create(title: 'Pokemon Sun', description: 'Pokémon Sun and Moon are role-playing video games with adventure elements, based in the fictional Alola region (which itself is loosely based on Hawaiian and Pacific Islander culture), presented in a third-person, overhead perspective. The player controls a young trainer who goes on a quest to catch and train creatures known as Pokémon, and win battles against other trainers.'. ESRB: 'E', link: '<iframe width="560" height="315" src="https://www.youtube.com/embed/fL6QuYi3rpo?ecver=1" frameborder="0" allowfullscreen></iframe>')
Game.create(title: 'Nioh', description: 'Nioh is an action role-playing game set in Japan during the year 1600, with players taking the role of an Irish samurai named William.[4] The player guides William on missions through enclosed environments fighting both human enemies and supernatural beings called yokai: missions are self-contained, hold alternate routes William can navigate, and selected from a menu rather than reached by navigating an open world.', ESRB: 'M', link: 'https://www.youtube.com/embed/aMTH7Byv5vE?ecver=1')
Game.create(title: 'Fallout 4', description: 'Fallout 4 gameplay is similar to that of Fallout 3 and Fallout: New Vegas, the previous two main entries in the series. Returning features include a camera that can switch between a first-person and third-person perspective, and the ability to roam anywhere on the map. Fallout 4 introduces new features including a layered armor system, base-building, a dynamic dialogue system featuring 111,000 lines of dialogue,[1] an in-depth crafting system which implements every lootable object in the game, and much more. Enemies such as mole rats, raiders, super-mutants, deathclaws, and feral ghouls return in Fallout 4, along with the companion Dogmeat.', ESRB: 'T', link: 'https://www.youtube.com/embed/GE2BkLqMef4?ecver=1')
Game.create(title: 'Pokemon X', description: 'Pokémon X and Y are role-playing video games with adventure elements, presented in a third-person, overhead perspective. It is also the first Pokémon games to include 3D functions, not only in the games overworld, but compatible with the 3D hardware of the Nintendo 3DS family of systems. The player controls a young trainer who goes on a quest to catch and train creatures known as Pokémon, and win battles against other trainers while training their own. ', ESRB: 'E', link: 'https://www.youtube.com/embed/WNr6wQfNfK4?ecver=1')
Game.create(title: 'Tales of Berseria', description: 'Tales of Berseria is a role-playing video game, where players navigate the games world through the games characters from a third-person perspective.[6] As with previous Tales games, characters can interact through Skits, animated clips that play outside cutscenes and battle: characters are represented by head-and-shoulder portraits, and conversations can range from serious to comedic. ', ESRB: 'T', link: 'https://www.youtube.com/embed/Wz1PxoQcMug?ecver=1')
Game.create(title: 'Fire Emblem Heroes', description: 'Beginning with a grid map that measures 8x6, players are able to summon characters from the Fire Emblem series to attack opposing enemies.[2] Players are free to create a team of up to four heroes to progress through the story, or fight against other players teams.
The games currency are known as "orbs", which can be used to acquire new heroes.[3] Missions costs are between one and 23 stamina to play while stamina is recovered at a rate of one point per five minutes, with a maximum of 99 stamina. Orbs are either earned by completing in-game activities or with in-app purchases.[3] Orbs can also be used to cast Lights Blessing which heals all of the players units, revives any of the players defeated units, makes all activation skills ready to activate and allows a players team to fight again; in addition, orbs can be used to permanently increase experience gained or maximum hero capacity (initialy 200), or to replenish stamina.', ESRB: 'E', link: 'https://www.youtube.com/embed/AWOcLSD_D1I?ecver=1')
